name: Profile Workflow

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  # Snake Graph
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
            dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Stats
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: anuraghazra/github-readme-stats@master
        with:
          username: ${{ github.repository_owner }}
          template: classic
          show_icons: true
          include_all_commits: true
